-- Create the media_storage table
CREATE TABLE IF NOT EXISTS media_storage (
     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     owner_id INT NULL,
     reference_type INT NOT NULL,
     reference_id INT NOT NULL,
     external_id VARCHAR(64) NOT NULL,
     URL VARCHAR(512) NOT NULL,
     mime_type VARCHAR(64) NOT NULL,
     created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
     updated_at TIMESTAMP(6) WITH TIME ZONE NULL
    );