-- Email/password login and roles
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(100) NULL;
ALTER TABLE users ALTER COLUMN firebase_user_id DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER';

-- A Firebase account can belong to at most one user
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_firebase_user_id ON users (firebase_user_id) WHERE firebase_user_id IS NOT NULL;

-- Refresh tokens are stored only as SHA-256 hashes so a database leak does not expose usable tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON refresh_tokens (user_id);
